# tools/creative_backend_tools.py
import os
import logging
import uuid
import time
import io
import base64
import tempfile
import datetime

# Initialize logger right after importing logging
logger = logging.getLogger(__name__)

# Core GenAI imports
from google import genai
from google.genai.types import (
    GenerateImagesConfig,
    GenerateVideosConfig,
    Image as GenAIImage,
    Video as GenAIVideo,
    EditImageConfig,
    SubjectReferenceImage,
    RawReferenceImage,
    MaskReferenceImage,
    StyleReferenceImage,
    EditMode,
    PersonGeneration,
)
from google.api_core.exceptions import GoogleAPIError

# Google Cloud Storage imports
from google.cloud import storage

# For environment variables
from dotenv import load_dotenv

# For image format detection (used in image-to-video, optional)
try:
    from PIL import Image as PILImage
except ImportError:
    PILImage = None
    logger.warning("Pillow not installed. Image format detection might be less robust.")


# Load environment variables
load_dotenv()

# --- GCS Configuration and Client Initialization ---
try:
    GCP_BUCKET_NAME = os.getenv("GCP_BUCKET_NAME")
    if not GCP_BUCKET_NAME:
        raise ValueError("GCP_BUCKET_NAME environment variable not set.")
    storage_client = storage.Client()
    bucket = storage_client.bucket(GCP_BUCKET_NAME)
    GCS_OUTPUT_PREFIX = os.getenv("OUTPUT_GCS_URI", "gs://").split("gs://", 1)[-1].split("/", 1)[-1].strip("/")
    if GCS_OUTPUT_PREFIX:
        GCS_OUTPUT_PREFIX += "/"
    else:
        GCS_OUTPUT_PREFIX = "generated_videos/"
    logger.info(f"Initialized GCS client for bucket: {GCP_BUCKET_NAME} with prefix: {GCS_OUTPUT_PREFIX}")
except Exception as e:
    logger.error(f"Failed to initialize GCS client: {e}")
    raise

# --- GenAI Client Initialization ---
try:
    # NOTE: With the public URL method, you no longer need the GOOGLE_APPLICATION_CREDENTIALS
    # environment variable for this specific function, as signing is not required.
    # The default credentials from the environment are sufficient.
    GOOGLE_PROJECT_ID = os.getenv("GOOGLE_PROJECT_ID")
    LOCATION = os.getenv("LOCATION")
    GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY")

    if not GOOGLE_PROJECT_ID or not LOCATION:
        raise ValueError("GOOGLE_PROJECT_ID or LOCATION environment variables not set.")

    if GOOGLE_API_KEY:
        genai_client = genai.Client(api_key=GOOGLE_API_KEY)
        logger.info("Initialized GenAI client with API Key.")
    else:
        genai_client = genai.Client(
            vertexai=True,
            project=GOOGLE_PROJECT_ID,
            location=LOCATION
        )
        logger.info(f"Initialized GenAI client with ADC, routed to Vertex AI project: {GOOGLE_PROJECT_ID}, location: {LOCATION}.")

except Exception as e:
    logger.error(f"Failed to initialize GenAI client: {e}")
    raise


# --- Core API Call Functions (These are now just regular async functions) ---

async def call_generate_image_api(prompt: str) -> str:
    """Calls Imagen model for image generation and returns a simple, public GCS URL."""
    try:
        logger.debug(f"Calling GenAI generate_images (Imagen 3) with prompt: '{prompt}'")
        response = genai_client.models.generate_images(
            model="imagen-3.0-generate-002",
            prompt=prompt,
            config=GenerateImagesConfig(
                number_of_images=1,
                aspect_ratio="1:1",
            )
        )

        if not response.generated_images:
            raise ValueError("No images generated by the API.")

        image_bytes = response.generated_images[0].image.image_bytes
        mime_type = response.generated_images[0].image.mime_type or "image/jpeg"

        file_name = f"generated_images/{uuid.uuid4()}.jpg"
        blob = bucket.blob(file_name)
        blob.upload_from_string(image_bytes, content_type=mime_type)
        gcs_uri = f"gs://{bucket.name}/{file_name}"
        logger.info(f"Generated image saved to GCS: {gcs_uri}")

        # ### OLD CODE (for Signed URL) ###
        # # This logic required a service account key for signing.
        # signed_url = blob.generate_signed_url(
        #     version="v4",
        #     expiration=datetime.timedelta(hours=1),
        #     method="GET",
        # )
        # logger.info(f"Generated signed URL: {signed_url}")
        # return signed_url
        
        # ### NEW CODE (for Public URL) ###
        # Construct the simple public URL string directly. This requires the object/bucket
        # to be publicly accessible.
        public_url = f"https://storage.mtls.cloud.google.com/{bucket.name}/{file_name}"
        logger.info(f"Generated public URL: {public_url}")
        return public_url

    except Exception as e:
        logger.error(f"Failed to generate image via GenAI API: {e}")
        raise

async def call_edit_image_api(reference_image_path: str, prompt: str) -> str:
    """Calls Imagen model for image editing using google.generativeai."""
    try:
        logger.debug(f"Calling GenAI edit_image (Imagen 3) for: '{reference_image_path}' with prompt: '{prompt}'")

        blob_path = reference_image_path.replace(f"gs://{bucket.name}/", "")
        blob = bucket.blob(blob_path)
        image_bytes_from_gcs = blob.download_as_bytes()
        image_mime_type_from_gcs = blob.content_type or "image/jpeg"

        base_genai_image = GenAIImage(
            image_bytes=image_bytes_from_gcs,
            mime_type=image_mime_type_from_gcs
        )

        model_name = "imagen-3.0-edit"

        reference_images_list = []
        try:
            ref_image_for_edit = SubjectReferenceImage(
                reference_id=1,
                image=base_genai_image,
                subject_type="object",
            )
            reference_images_list.append(ref_image_for_edit)
        except Exception as ref_err:
            logger.warning(f"Could not create SubjectReferenceImage for editing (will try without it): {ref_err}")

        response = genai_client.models.edit_image(
            model=model_name,
            base_image=base_genai_image,
            prompt=prompt,
            config=EditImageConfig(
                number_of_images=1,
                edit_mode=EditMode.DEFAULT,
                reference_images=reference_images_list,
                safety_filter_level="BLOCK_MOST",
            )
        )

        if not response.edited_images:
            raise ValueError("No images edited by the API.")

        edited_image_bytes = response.edited_images[0].image.image_bytes
        edited_mime_type = response.edited_images[0].image.mime_type or "image/jpeg"

        file_name = f"edited_images/{uuid.uuid4()}.jpg"
        blob = bucket.blob(file_name)
        blob.upload_from_string(edited_image_bytes, content_type=edited_mime_type)
        gcs_uri = f"gs://{bucket.name}/{file_name}"
        logger.info(f"Edited image saved to GCS: {gcs_uri}")
        return gcs_uri

    except Exception as e:
        logger.error(f"Failed to edit image via GenAI API: {e}")
        raise


async def call_generate_video_from_text_api(prompt: str, negative_prompt: str = "ugly, low quality", aspect_ratio: str = "16:9", duration_seconds: int = 8) -> str:
    """Calls Veo 2 model for video generation from text using google.generativeai."""
    logger.debug(f"Calling Veo 2 (text-to-video) for prompt: '{prompt}'")
    try:
        operation = genai_client.models.generate_videos(
            model="veo-3.0-generate-preview",
            prompt=prompt,
            config=GenerateVideosConfig(
                aspect_ratio=aspect_ratio,
                number_of_videos=1,
                negative_prompt=negative_prompt,
                duration_seconds=duration_seconds,
            ),
        )

        while not operation.done:
            logger.info("Veo text-to-video operation not done yet, waiting...")
            time.sleep(15)
            operation = genai_client.operations.get(operation.name)

        if operation.response and operation.result.generated_videos:
            generated_video_obj = operation.result.generated_videos[0]
            if not isinstance(generated_video_obj.video, GenAIVideo) or not generated_video_obj.video.uri:
                raise ValueError("Generated video object structure unexpected or missing URI for download.")

            logger.info(f"Attempting client.files.download for URI: {generated_video_obj.video.uri}")
            genai_client.files.download(file=generated_video_obj.video)

            video_mime_type = getattr(generated_video_obj.video, "mime_type", "video/mp4")
            suffix = f'.{video_mime_type.split("/")[-1]}' if isinstance(video_mime_type, str) and "/" in video_mime_type else ".mp4"

            temp_file_path = None
            try:
                with tempfile.NamedTemporaryFile(delete=False, suffix=suffix) as temp_file:
                    temp_file_path = temp_file.name
                generated_video_obj.video.save(temp_file_path)
                logger.info(f"Video saved to temporary file: {temp_file_path}")

                gcs_file_name = f"{GCS_OUTPUT_PREFIX}{uuid.uuid4()}{suffix}"
                blob = bucket.blob(gcs_file_name)
                blob.upload_from_filename(temp_file_path, content_type=video_mime_type)
                gcs_link = f"gs://{bucket.name}/{gcs_file_name}"
                logger.info(f"Video uploaded to GCS: {gcs_link}")
                return gcs_link
            finally:
                if temp_file_path and os.path.exists(temp_file_path):
                    os.remove(temp_file_path)

        elif operation.error:
            raise GoogleAPIError(operation.error.message)
        else:
            raise ValueError("Video generation completed with unexpected final state.")

    except GoogleAPIError as api_err:
        logger.error(f"Google API Error during text video generation: {api_err.message}")
        raise
    except Exception as e:
        logger.error(f"An unexpected error occurred during text video generation: {e}")
        raise

async def call_generate_video_from_image_api(image_bytes: bytes, image_mime_type: str, prompt: str = "", negative_prompt: str = "ugly, low quality", aspect_ratio: str = "16:9", duration_seconds: int = 8) -> str:
    """Calls Veo 2 model for video generation from an image using google.generativeai."""
    logger.debug(f"Calling Veo 2 (image-to-video) for image ({image_mime_type}) and prompt: '{prompt}'")
    try:
        genai_image = GenAIImage(
            image_bytes=image_bytes,
            mime_type=image_mime_type,
        )

        operation = genai_client.models.generate_videos(
            model="veo-3.0-generate-preview",
            image=genai_image,
            prompt=prompt,
            config=GenerateVideosConfig(
                aspect_ratio=aspect_ratio,
                number_of_videos=1,
                negative_prompt=negative_prompt,
                duration_seconds=duration_seconds,
            ),
        )

        while not operation.done:
            logger.info("Veo image-to-video operation not done yet, waiting...")
            time.sleep(15)
            operation = genai_client.operations.get(operation.name)

        if operation.response and operation.result.generated_videos:
            generated_video_obj = operation.result.generated_videos[0]
            if not isinstance(generated_video_obj.video, GenAIVideo) or not generated_video_obj.video.uri:
                raise ValueError("Generated video object structure unexpected or missing URI for download.")

            logger.info(f"Attempting client.files.download for URI: {generated_video_obj.video.uri}")
            genai_client.files.download(file=generated_video_obj.video)

            video_mime_type = getattr(generated_video_obj.video, "mime_type", "video/mp4")
            suffix = f'.{video_mime_type.split("/")[-1]}' if isinstance(video_mime_type, str) and "/" in video_mime_type else ".mp4"

            temp_file_path = None
            try:
                with tempfile.NamedTemporaryFile(delete=False, suffix=suffix) as temp_file:
                    temp_file_path = temp_file.name
                generated_video_obj.video.save(temp_file_path)
                logger.info(f"Video saved to temporary file: {temp_file_path}")

                gcs_file_name = f"{GCS_OUTPUT_PREFIX}{uuid.uuid4()}{suffix}"
                blob = bucket.blob(gcs_file_name)
                blob.upload_from_filename(temp_file_path, content_type=video_mime_type)
                gcs_link = f"gs://{bucket.name}/{gcs_file_name}"
                logger.info(f"Video uploaded to GCS: {gcs_link}")
                return gcs_link
            finally:
                if temp_file_path and os.path.exists(temp_file_path):
                    os.remove(temp_file_path)

        elif operation.error:
            raise GoogleAPIError(operation.error.message)
        else:
            raise ValueError("Video generation completed with unexpected final state.")

    except GoogleAPIError as api_err:
        logger.error(f"Google API Error during image video generation: {api_err.message}")
        raise
    except Exception as e:
        logger.error(f"An unexpected error occurred during image video generation: {e}")
        raise
